spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"
  cache:
    caffeine:
      spec: expireAfterWrite=6s

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL

stripe:
  secretKey=:sk_test_51MG8ddGAEiSOTIcIX6J07T6riIY0hKgUlobOHo4OFGNDNrwrpWLx1lAetpjdYPDaiTILqdY1wA0PVKBA3qf2a3Og00fcK1jGYL